### ISSUE TITLE
GetFileSettings needs to run in Non Authenticated state

### ISSUE THREAD

**Issue by johnnyb** [johnnyb/ntag424-java#3]
GetFileSettings needs to run in Non Authenticated state

[Submitted via email by AndroidCrypto]

**Comment by johnnyb** [comment]
The table on pg. 44 indicates it should run in MAC mode, which implies an authenticated state, but I will look into it (and maybe other commands that may not need authentication).

**Comment by MichaelsPlayground** [comment]
There is another rule "overriding" the data on pg. 44 - see "**8.2.3.5 Communication modes**": 
Page 14: "If there is **no active authentication**, the command and response are **sent in plain** (or the
command is rejected in the case an authentication is required)".

It is important for a NFC reader to get the FileSettings without authentication, because the GetFileSettings response defines which key has to be used for e.g. a read access.

**Comment by johnnyb** [comment]
Interesting!  I didn't realize that it had that exception.  I now have nxpMacCommand and nxpEncryptedCommand short-circuiting to nxpPlainCommand if !isLoggedIn().  Commit 6a8b94a.

**Comment by AndroidCrypto** [comment]
Confirmed, solution is working, thank you.
Greetings
Michael
